using UnityEngine;
using TMPro; // 1. CRITICAL: Add this namespace to handle text updates!

public class MathOrb : MonoBehaviour
{
    [System.Serializable]
    public struct BoostData
    {
        public string stat;  // Target Player Stat (Attack, Max health, Movement, Defense, Heal)
        public int value;    // Boost value generated by RNG
    }

    [Header("GDD Data Structure")]
    public string id;
    public int op1;
    public int op2;
    public string op;
    public int res;
    public BoostData boost;

    [Header("Visual References")]
    public TMP_Text floatingOperatorText; // 2. SLOT FOR THE ORB'S TEXT MESH

    // This initialization method is triggered by your OrbSpawner script at instantiation
    public void InitializeOrb(int operand1, int operand2, string operation, int correctResult, string targetStat, int boostValue)
    {
        id = System.Guid.NewGuid().ToString();
        op1 = operand1;
        op2 = operand2;
        op = operation;
        res = correctResult;

        boost.stat = targetStat;
        boost.value = boostValue;

        // 3. DYNAMICALLY UPDATE THE TEXT OVER THE ORB
        if (floatingOperatorText != null)
        {
            // If the operation is a multiplication star, you can make it look cleaner as an 'X'
            if (operation == "*")
            {
                floatingOperatorText.text = "×";
            }
            else
            {
                floatingOperatorText.text = operation;
            }
        }
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        // Only run the math window routine if Toto himself enters the zone!
        if (collision.CompareTag("Player"))
        {
            Debug.Log($"[SUCCESS] Toto entered Math Orb zone: {gameObject.name}");

            MathVerificationController panelController = FindFirstObjectByType<MathVerificationController>();

            if (panelController != null)
            {
                panelController.OpenQuestionWindow(this);
            }
            else
            {
                Debug.LogError("CRITICAL ERROR: MathVerificationController component is missing from your scene GameManager object!");
            }
        }
    }
}